resources:
  - name: repo-test
    type: git
    source:
      uri: https://github.com/benjisu03/pipeline-test.git
      branch: master

jobs:
  - name: test
    public: true
    plan:
      - get: repo
        resource: repo-test
        trigger: false

      - task: testing
        file: repo/ci/scripts/prepare-project.yml
